name: '毒鸡汤'

on:
  schedule:
    - cron: '15 0-15 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: node ./plugins/dujitang.js
        env:
          bot_api: ${{ secrets.bot_api }}